import { Geist, Geist_Mono } from "next/font/google";


import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css"
import 'bootstrap-icons/font/bootstrap-icons.css';
import Navbar from "@/components/blocks/Navbar";
import Footer from "@/components/blocks/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar />

        <main className="flex-grow-1">
        {children}  
      </main>
    
        <Footer />

      </body>
    </html>
  );
}
